const testimonials = [
    {
        id: 1,
        name: "Anita Sharma",
        position: "Endocrinologist",
        company: "CarePlus Hospital",
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f",
        text: "The diabetes prediction tool is remarkably accurate and easy to use, making it a fantastic resource for my patients to monitor their risks.",
        rating: 5,
    },
    {
        id: 2,
        name: "Rahul Verma",
        position: "Software Engineer",
        company: "TechTrend Innovations",
        image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
        text: "I love how intuitive this website is! The visualizations helped me understand my health data clearly, and the predictions were spot-on.",
        rating: 4.5,
    },
    {
        id: 3,
        name: "Meena Patel",
        position: "Yoga Instructor",
        company: "Serenity Studio",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2",
        text: "This tool empowered me to take control of my health. The detailed insights and user-friendly design make it a must-have for wellness enthusiasts.",
        rating: 4.8,
    },
    {
        id: 4,
        name: "Vikram Singh",
        position: "General Practitioner",
        company: "CityHealth Clinic",
        image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
        text: "As a doctor, I value the transparency of this platform. It’s an excellent way to educate patients about diabetes risks with reliable data.",
        rating: 5,
    },
    {
        id: 5,
        name: "Lakshmi Nair",
        position: "Dietitian",
        company: "NutriFit Solutions",
        image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
        text: "The prediction model is impressive, and the visualizations are perfect for explaining complex health metrics to my clients in a simple way.",
        rating: 4.7,
    },
    {
        id: 6,
        name: "Kiran Reddy",
        position: "Data Analyst",
        company: "InfoGrow Analytics",
        image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
        text: "The website’s data-driven approach is fantastic. It gave me actionable insights into my health, presented in a sleek and modern interface.",
        rating: 4.6,
    },
    {
        id: 7,
        name: "Sneha Gupta",
        position: "Pharmacist",
        company: "MediCare Pharmacy",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956",
        text: "This platform is a game-changer for preventive healthcare. The predictions are reliable, and the about page builds trust with clear goals.",
        rating: 5,
    },
    {
        id: 8,
        name: "Aditya Rao",
        position: "Fitness Trainer",
        company: "PeakPulse Gym",
        image: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg",
        text: "I recommend this website to all my clients. It’s easy to navigate, and the health insights help them stay motivated to live healthier lives.",
        rating: 4.5,
    },
    {
        id: 9,
        name: "Deepa Iyer",
        position: "Wellness Coach",
        company: "BalancePoint Wellness",
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f",
        text: "The visualizations are top-notch! They make it so easy to understand diabetes risk factors, and my clients love the clarity it provides.",
        rating: 4.9,
    },
    {
        id: 10,
        name: "Suresh Menon",
        position: "Retired Teacher",
        company: "Anna University",
        image: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
        text: "As someone at risk, I found this tool incredibly helpful. It’s like having a personal health guide, with clear and trustworthy predictions.",
        rating: 4.7,
    },
    {
        id: 11,
        name: "Nisha Kapoor",
        position: "Health Journalist",
        company: "VitalNews Media",
        image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
        text: "This website is a goldmine for health reporting. The data visualizations and prediction accuracy make it a credible source for my articles.",
        rating: 5,
    },
    {
        id: 12,
        name: "Ravi Kumar",
        position: "Nurse",
        company: "Hope Medical Center",
        image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
        text: "The tool’s simplicity and precision are impressive. It’s a great way to encourage patients to take proactive steps toward better health.",
        rating: 4.8,
    },
    {
        id: 13,
        name: "Pooja Desai",
        position: "Marketing Manager",
        company: "GrowEasy Solutions",
        image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e",
        text: "I was blown away by how easy it was to use this website. The predictions gave me a wake-up call to prioritize my health.",
        rating: 4.6,
    },
    {
        id: 14,
        name: "Mohan Das",
        position: "Cardiologist",
        company: "HeartCare Institute",
        image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg",
        text: "The diabetes prediction tool aligns well with clinical assessments, making it a valuable asset for patient education and risk management.",
        rating: 5,
    },
    {
        id: 15,
        name: "Tara Bose",
        position: "Lifestyle Blogger",
        company: "LiveWell Blog",
        image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6",
        text: "This website makes health data fun to explore! The visualizations are engaging, and the predictions are a great conversation starter.",
        rating: 4.7,
    },
    {
        id: 16,
        name: "Amit Joshi",
        position: "Gym Owner",
        company: "PowerFit Studios",
        image: "https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg",
        text: "The diabetes prediction feature is a hit with my members. It’s straightforward, informative, and motivates them to stay active.",
        rating: 4.5,
    },
    {
        id: 17,
        name: "Rekha Pillai",
        position: "Home Maker",
        company: "N/A",
        image: "https://images.unsplash.com/photo-1603415526960-f7e0328c63b1",
        text: "I’m not tech-savvy, but this website was so easy to use. The health insights helped me make better choices for my family.",
        rating: 4.8,
    },
    {
        id: 18,
        name: "Sanjay Thakur",
        position: "Corporate Wellness Consultant",
        company: "ThriveAtWork",
        image: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg",
        text: "This platform is a standout for workplace wellness programs. The data-driven predictions are perfect for promoting employee health.",
        rating: 5,
    },
    {
        id: 19,
        name: "Divya Arora",
        position: "Student",
        company: "City University",
        image: "https://images.unsplash.com/photo-1593529467220-9d721ceb9a78",
        text: "As a health sciences student, I found this tool educational and engaging. The visualizations made learning about diabetes fun!",
        rating: 4.6,
    },
    {
        id: 20,
        name: "Rakesh Malhotra",
        position: "Entrepreneur",
        company: "HealthTech Ventures",
        image: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg",
        text: "The website’s sleek design and accurate predictions are impressive. It’s a brilliant tool for anyone looking to stay ahead of health risks.",
        rating: 4.9,
    },
];

export default testimonials;